### ISSUE TITLE
Please release updated build on bukkit plugins

### ISSUE THREAD

**Issue by tronman2020** [mstiles92/HardcoreDeathBan#14]
The files on bukkit are severely outdated! please update builds on bukkit plugins website?
This is and has always been the absolute best death ban plugin!
I am using latest spigot

**Comment by tronman2020** [comment]
Or Jenkins?

**Comment by mstiles92** [comment]
The files on BukkitDev have not been updated on purpose. The plugin is not in a stable state at this point in time, as I am in the middle of rewriting a large portion of it. You can access dev builds on the [Jenkins](https://mstiles92.com/jenkins/), but the current one probably will not even work at this point in time. I will update the BukkitDev page with a new download when I am finished rewriting it and have a stable build.

**Comment by tronman2020** [comment]
Oh okay, thank you I look forward to it!

**Comment by tronman2020** [comment]
Thank you for linking the Jenkins website, I could not find any links to it
on your devpage or github. I have bookmarked it. I am a huge fan of your
work and I look forward to a stable build! I think your plugin is the only
death-ban plugin currently being worked on. I have searched bukkit high and
low for an alternative and they all appear abandoned.

On Tue, Jan 27, 2015 at 5:53 AM, Matthew Stiles <notifications@github.com>
wrote:

> The files on BukkitDev have not been updated on purpose. The plugin is not
> in a stable state at this point in time, as I am in the middle of rewriting
> a large portion of it. You can access dev builds on the Jenkins
> <https://mstiles92.com/jenkins/>, but the current one probably will not
> even work at this point in time. I will update the BukkitDev page with a
> new download when I am finished rewriting it and have a stable build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mstiles92/HardcoreDeathBan/issues/14#issuecomment-71650420>
> .
>



-- 
V/R Brian
